import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Footer from '@/components/footer'
import Navigationbar from "@/components/navigationbar";
import { LinkItem } from "@/shared/types";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const linkList: LinkItem[] = [
  {
    href: "/",
    label: "Egg"
  },
  {
    href: "/",
    label: "Mount"
  }
]

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <Navigationbar linklist={linkList} >
          <Link href="/">
            <b>TES</b>
          </Link>
        </Navigationbar>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
